package com.example.allinoneapp.utilClass

import kotlin.collections.ArrayList

class PeopleRepo {

//    fun getPeople(): List<Person> {
//        val people: MutableList<Person> = ArrayList(45)
//        people.add(Person("George", "Washington"))
//        people.add(Person("John", "Adams"))
//        people.add(Person("Thomas", "Jefferson"))
//        people.add(Person("James", "Madison"))
//        people.add(Person("James", "Monroe"))
//        people.add(Person("John Quincy", "Adams"))
//        people.add(Person("Andrew", "Jackson"))
//        people.add(Person("Martin", "Van Buren"))
//        people.add(Person("William", "Harrison"))
//        people.add(Person("John", "Tyler"))
//        people.add(Person("Zachary", "Taylor"))
//        people.add(Person("Millard", "Fillmore"))
//        people.add(Person("Franklin", "Pierce"))
//        people.add(Person("James", "Buchanan"))
//        people.add(Person("Abraham", "Lincoln"))
//        people.add(Person("Andrew", "Johnson"))
//        people.add(Person("Ulysses", "Grant"))
//        people.add(Person("Rutherford", "Hayes"))
//        people.add(Person("James", "Garfield"))
//        people.add(Person("Chester", "Arthur"))
//        people.add(Person("Grover", "Cleveland"))
//        people.add(Person("Benjamin", "Harrison"))
//        people.add(Person("William", "McKinley"))
//        people.add(Person("Theodore", "Roosevelt"))
//        people.add(Person("William", "Taft"))
//        people.add(Person("Woodrow", "Wilson"))
//        people.add(Person("Warren", "Harding"))
//        people.add(Person("Calvin", "Coolidge"))
//        people.add(Person("Herbert", "Hoover"))
//        people.add(Person("Harry", "Truman"))
//        people.add(Person("Dwight", "Eisenhower"))
//        people.add(Person("John", "Kennedy"))
//        people.add(Person("Lyndon", "Johnson"))
//        people.add(Person("Richard", "Nixon"))
//        people.add(Person("Gerald", "Ford"))
//        people.add(Person("Jimmy", "Carter"))
//        people.add(Person("Ronald", "Reagan"))
//        people.add(Person("George H.W.", "Bush"))
//        people.add(Person("Bill", "Clinton"))
//        people.add(Person("George W.", "Bush"))
//        people.add(Person("Barack", "Obama"))
//        people.add(Person("Donald", "Trump"))
//        return people
//    }

    fun getPeople(): List<Person> {
        val people: MutableList<Person> = ArrayList(45)
        people.add(Person("George", "Washington","30-03-2012"))
        people.add(Person("John", "Adams","28-03-2013"))
        people.add(Person("Thomas", "Jefferson","02-04-2012"))
        people.add(Person("James", "Madison","30-03-2012"))
        people.add(Person("James", "Monroe","31-03-2012"))
        people.add(Person("John Quincy", "Adams","02-04-2012"))
        people.add(Person("Andrew", "Jackson","30-03-2012"))
        people.add(Person("Martin", "Van Buren","28-03-2013"))
        people.add(Person("William", "Harrison","02-04-2012"))
        people.add(Person("John", "Tyler","30-03-2012"))
        people.add(Person("Zachary", "Taylor","31-03-2012"))
        people.add(Person("Millard", "Fillmore","02-04-2012"))
        people.add(Person("Franklin", "Pierce","30-03-2012"))
        people.add(Person("James", "Buchanan","28-03-2013"))
        people.add(Person("Abraham", "Lincoln","02-04-2012"))
        people.add(Person("Andrew", "Johnson","30-03-2012"))
        people.add(Person("Ulysses", "Grant","31-03-2012"))
        people.add(Person("Rutherford", "Hayes","02-04-2012"))
        people.add(Person("James", "Garfield","30-03-2012"))
        people.add(Person("Chester", "Arthur","28-03-2013"))
        people.add(Person("Grover", "Cleveland","02-04-2012"))
        people.add(Person("Benjamin", "Harrison","30-03-2012"))
        people.add(Person("William", "McKinley","31-03-2012"))
        people.add(Person("Theodore", "Roosevelt","02-04-2012"))
        people.add(Person("William", "Taft","30-03-2012"))
        people.add(Person("Woodrow", "Wilson","28-03-2013"))
        people.add(Person("Warren", "Harding","02-04-2012"))
        people.add(Person("Calvin", "Coolidge","30-03-2012"))
        people.add(Person("Herbert", "Hoover","31-03-2012"))
        people.add(Person("Harry", "Truman","02-04-2012"))
        people.add(Person("Dwight", "Eisenhower","30-03-2012"))
        people.add(Person("John", "Kennedy","28-03-2013"))
        people.add(Person("Lyndon", "Johnson","02-04-2012"))
        people.add(Person("Richard", "Nixon","30-03-2012"))
        people.add(Person("Gerald", "Ford","31-03-2012"))
        people.add(Person("Jimmy", "Carter","02-04-2012"))
        people.add(Person("Ronald", "Reagan","30-03-2012"))
        people.add(Person("George H.W.", "Bush","28-03-2013"))
        people.add(Person("Bill", "Clinton","02-04-2012"))
        people.add(Person("George W.", "Bush","30-03-2012"))
        people.add(Person("Barack", "Obama","31-03-2012"))
        people.add(Person("Donald", "Trump","02-04-2012"))
        return people
    }


//    fun getPeopleSorted(): List<Person>? {
//        val people = getPeople()
//        Collections.sort(people)
//        return people
//    }

}